### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by ocowchun** [sudo-recruit/pizza#4]
## 1. Duplicate in Local Machine
通常會建議將全部的東西都放在 vagrant，也就是說以本案例來說，會建議開兩台vm(consul-server,cousl-client)

## 2. `recipes/westudent-jb.rb` 建議更名為 `rails-app.rb`
比較符合本檔案的用途，用來設定 rails app 的相關設定

## 3. monit 建議從 `recipes/nginx.rb` 抽離出來
rails app 跟 nginx 都會用到 monit，所以建議抽離出來。

**Comment by henry40408** [comment]
- [ ] 通常會建議將全部的東西都放在 vagrant，也就是說以本案例來說，會建議開兩台 VM (consul-server, kitchen 啟動的 application instance)
- [ ] `recipes/westudent-jb.rb` 建議更名為 `rails-app.rb`

**Comment by henry40408** [comment]
feedback has been accepted and release [v1.1.0](https://github.com/sudo-recruit/pizza/tree/1.1.0)
